#!/bin/bash
echo $1
for f in $(ls $1); do
	if [ -f $1$f ]; 
	then # for files
		filename=$1$f
		output=$(cat $1$f | grep $2 -n)
		output=$filename:$output
		echo $output | grep $2 >> $3
	else
		./$0 $1$f/ $2 $3
	fi
done 