#!/bin/bash
nWord=0
i=0
flag=0

file=$(tr '\n' ' ' < $1)

for word in $file
do
	while [ $i -lt $nWord ]
	do
		#echo ${words[$i]}
		if [ "$word" == "${words[$i]}" ] # if we did encounter this word before
		then
			let counts[$i]=counts[$i]+1
			flag=1
		fi
		let i=i+1
	done
	i=0
	if [ $flag -eq 0 ] 
	then
		echo $word
		words[$nWord]=$word
		counts[$nWord]=1
		let nWord=$nWord+1
	fi
	flag=0
done

while [ $i -lt $nWord ]
	do		
	echo ${words[$i]} ":" ${counts[$i]}
	let i=i+1
done